// Auto-generated by build_story.js from WesthagenMarktplatz_Demo.html — 1:1 linear port.
// This is scaffold data: a node graph keyed by id with "next" pointers instead of
// a flat array index, so branch points (type:"choice") and endings (type:"ending")
// can be inserted later without renumbering everything.
// Branch content itself is NOT part of this port — see plan for follow-up iteration.
const STORY = {
  "m1": {
    "type": "date",
    "day": 5,
    "time": "08:00",
    "text": "Monday",
    "id": "m1",
    "next": "m2"
  },
  "m2": {
    "type": "system",
    "day": 5,
    "time": "08:02",
    "text": "You joined the group",
    "memberJoin": true,
    "id": "m2",
    "next": "m3"
  },
  "m3": {
    "type": "msg",
    "day": 5,
    "time": "08:14",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Morning, everyone! 👋 Summer holidays are right around the corner – is anyone actually staying here in Westhagen this year, or is everyone heading off somewhere?",
    "id": "m3",
    "next": "m4"
  },
  "m4": {
    "type": "msg",
    "day": 5,
    "time": "08:16",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "I just wanted to let you know, there's still a good amount of this year's neighbourhood budget sitting unused. Might be worth putting it toward something.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m4",
    "next": "m5"
  },
  "m5": {
    "type": "msg",
    "day": 5,
    "time": "08:19",
    "sender": "Birgit",
    "initial": "B",
    "bg": "#993c1d",
    "fg": "#fae8e0",
    "text": "We're staying, holidays for four just aren't doable this year 😅",
    "reactions": [
      {
        "emoji": "😅",
        "count": 5
      }
    ],
    "id": "m5",
    "next": "m6"
  },
  "m6": {
    "type": "msg",
    "day": 5,
    "time": "08:23",
    "sender": "Younes",
    "initial": "Y",
    "bg": "#854f0b",
    "fg": "#faeeda",
    "text": "Same here, six weeks with no plan and three kids won't end well 😬",
    "reactions": [
      {
        "emoji": "😬",
        "count": 4
      },
      {
        "emoji": "😂",
        "count": 3
      }
    ],
    "id": "m6",
    "next": "m7"
  },
  "m7": {
    "type": "msg",
    "day": 5,
    "time": "08:27",
    "sender": "Petra",
    "initial": "P",
    "bg": "#993556",
    "fg": "#fbeaf0",
    "text": "Probably goes for a lot of us here, right? Some kind of activity would be good 🤔",
    "reactions": [
      {
        "emoji": "👍",
        "count": 6
      }
    ],
    "id": "m7",
    "next": "m8"
  },
  "m8": {
    "type": "msg",
    "day": 5,
    "time": "08:34",
    "sender": "Sarah",
    "isMe": true,
    "text": "Hey, I'm new here 🙋‍♀️ found the QR code on the pallet benches by the tree and just had to join. Don't have kids myself, but doing something together on the square sounds really nice",
    "id": "m8",
    "next": "m9"
  },
  "m9": {
    "type": "msg",
    "day": 5,
    "time": "08:37",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Welcome, Sarah! Glad you're here. Sounds like there's real demand – what if we shaped the holidays ourselves? Let's make it official:",
    "reactions": [
      {
        "emoji": "👍",
        "count": 15
      },
      {
        "emoji": "🙌",
        "count": 8
      }
    ],
    "id": "m9",
    "next": "m10"
  },
  "m10": {
    "type": "poll",
    "day": 5,
    "time": "08:38",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "question": "Wolfsburg Plays! Should we build a kids' play space together this summer?",
    "options": [
      "Yes, let's do it! 🙌",
      "Not really for me"
    ],
    "id": "m10",
    "next": "m11"
  },
  "m11": {
    "type": "msg",
    "day": 5,
    "time": "08:40",
    "sender": "Mariia",
    "initial": "M",
    "bg": "#185fa5",
    "fg": "#e6f1fb",
    "text": "Just voted! Can't wait 😍",
    "pollVotes": [
      11,
      1
    ],
    "id": "m11",
    "next": "m12"
  },
  "m12": {
    "type": "msg",
    "day": 5,
    "time": "08:43",
    "sender": "Sven",
    "initial": "S",
    "bg": "#534ab7",
    "fg": "#eeedfe",
    "text": "Same here, better than another summer of complaining like last year 😂",
    "pollVotes": [
      18,
      2
    ],
    "id": "m12",
    "next": "m13"
  },
  "m13": {
    "type": "system",
    "day": 5,
    "time": "08:45",
    "text": "Poll is open until tomorrow.",
    "pollVotes": [
      21,
      3
    ],
    "id": "m13",
    "next": "m14"
  },
  "m14": {
    "type": "transition",
    "toDay": 6,
    "arriveTime": "09:00",
    "pollVotes": [
      556,
      175
    ],
    "id": "m14",
    "next": "m15"
  },
  "m15": {
    "type": "date",
    "day": 6,
    "time": "09:00",
    "text": "Tuesday",
    "id": "m15",
    "next": "m16"
  },
  "m16": {
    "type": "msg",
    "day": 6,
    "time": "09:05",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Poll's closed! 731 of 1,042 households voted, 76% in favor 🎉 “Wolfsburg Plays!” is officially happening this summer.",
    "pollVotes": [
      556,
      175
    ],
    "pollClose": true,
    "reactions": [
      {
        "emoji": "🎉",
        "count": 420
      },
      {
        "emoji": "🙌",
        "count": 230
      },
      {
        "emoji": "❤️",
        "count": 150
      }
    ],
    "id": "m16",
    "next": "m17"
  },
  "m17": {
    "type": "msg",
    "day": 6,
    "time": "09:07",
    "sender": "Karin",
    "initial": "K",
    "bg": "#2f7d4f",
    "fg": "#e1f4e7",
    "text": "Yesss, let's go! 🙌",
    "reactions": [
      {
        "emoji": "🙌",
        "count": 7
      }
    ],
    "id": "m17",
    "next": "m18"
  },
  "m18": {
    "type": "msg",
    "day": 6,
    "time": "09:09",
    "sender": "Soraya",
    "initial": "S",
    "bg": "#c9912e",
    "fg": "#fcf1da",
    "text": "So happy about this 💛",
    "reactions": [
      {
        "emoji": "❤️",
        "count": 9
      }
    ],
    "id": "m18",
    "next": "m19"
  },
  "m19": {
    "type": "msg",
    "day": 6,
    "time": "09:10",
    "sender": "Marie",
    "initial": "M",
    "bg": "#3d7a8f",
    "fg": "#e2f1f4",
    "text": "👍",
    "id": "m19",
    "next": "m20"
  },
  "m20": {
    "type": "msg",
    "day": 6,
    "time": "09:12",
    "sender": "Heike",
    "initial": "H",
    "bg": "#8f4b6b",
    "fg": "#f7e6ec",
    "text": "About time we did something here",
    "reactions": [
      {
        "emoji": "👍",
        "count": 6
      }
    ],
    "id": "m20",
    "next": "m21"
  },
  "m21": {
    "type": "msg",
    "day": 6,
    "time": "09:14",
    "sender": "Jens",
    "initial": "J",
    "bg": "#5a8f3d",
    "fg": "#eef6e2",
    "text": "In! Let's see what we come up with",
    "reactions": [
      {
        "emoji": "👍",
        "count": 5
      }
    ],
    "id": "m21",
    "next": "m22"
  },
  "m22": {
    "type": "msg",
    "day": 6,
    "time": "09:20",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Before we start planning anything – who's actually joining, and with how many kids? Quick poll, pick everything that applies to your household:",
    "reactions": [
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m22",
    "next": "m23"
  },
  "m23": {
    "type": "poll",
    "day": 6,
    "time": "09:21",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "multi": true,
    "question": "Who's in, and with whom?",
    "options": [
      "Toddler (under 3)",
      "Kid (3–10)",
      "Teenager (10+)",
      "No kids, but happy to help anyway"
    ],
    "id": "m23",
    "next": "m24"
  },
  "m24": {
    "type": "system",
    "day": 6,
    "time": "09:23",
    "text": "Poll is open until tomorrow morning.",
    "id": "m24",
    "next": "m25"
  },
  "m25": {
    "type": "msg",
    "day": 6,
    "time": "14:32",
    "sender": "Fatima",
    "initial": "F",
    "bg": "#2f5a8f",
    "fg": "#e1ecf6",
    "text": "Just voted, two kids here, both 3-10",
    "pollVotes": [
      9,
      16,
      11,
      7
    ],
    "id": "m25",
    "next": "m26"
  },
  "m26": {
    "type": "msg",
    "day": 6,
    "time": "15:10",
    "sender": "Frank",
    "initial": "F",
    "bg": "#8f6b2f",
    "fg": "#f6eddc",
    "text": "One teenager in this house, he's got nothing better to do this summer anyway 😄",
    "pollVotes": [
      15,
      23,
      19,
      11
    ],
    "id": "m26",
    "next": "m27"
  },
  "m27": {
    "type": "msg",
    "day": 6,
    "time": "16:48",
    "sender": "Aylin",
    "initial": "A",
    "bg": "#6b3d8f",
    "fg": "#ede2f6",
    "text": "Voted for toddler and kid, we're in with both",
    "pollVotes": [
      24,
      32,
      25,
      16
    ],
    "id": "m27",
    "next": "m28"
  },
  "m28": {
    "type": "transition",
    "toDay": 7,
    "arriveTime": "08:51",
    "pollVotes": [
      58,
      137,
      83,
      53
    ],
    "id": "m28",
    "next": "m29"
  },
  "m29": {
    "type": "date",
    "day": 7,
    "time": "08:51",
    "text": "Wednesday",
    "id": "m29",
    "next": "m30"
  },
  "m30": {
    "type": "msg",
    "day": 7,
    "time": "08:51",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Poll's closed! Looks like there's quite a crowd – around 280 kids are registered across all age groups. Don't worry, that doesn't mean all of them at once – realistically we should plan for about 30 kids being here at the same time. That's actually a really workable number to design around.",
    "pollVotes": [
      58,
      137,
      83,
      53
    ],
    "pollClose": true,
    "id": "m30",
    "next": "m31"
  },
  "m31": {
    "type": "msg",
    "day": 7,
    "time": "08:54",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Alright, let's get into it then – what should we actually build here?",
    "reactions": [
      {
        "emoji": "🙌",
        "count": 9
      }
    ],
    "id": "m31",
    "next": "m32"
  },
  "m32": {
    "type": "msg",
    "day": 7,
    "time": "10:17",
    "sender": "Jana",
    "initial": "J",
    "bg": "#2f8f7a",
    "fg": "#dff5f0",
    "text": "A sandbox would be great for the little ones, somewhere separate from the big kids running around 👶",
    "reactions": [
      {
        "emoji": "👍",
        "count": 14
      },
      {
        "emoji": "💡",
        "count": 6
      }
    ],
    "id": "m32",
    "next": "m33"
  },
  "m33": {
    "type": "msg",
    "day": 7,
    "time": "10:19",
    "sender": "Aylin",
    "initial": "A",
    "bg": "#6b3d8f",
    "fg": "#ede2f6",
    "text": "With a toddler myself, I'd really love to be able to sit close by and actually watch her while she plays 👀",
    "reactions": [
      {
        "emoji": "🙋",
        "count": 9
      }
    ],
    "id": "m33",
    "next": "m34"
  },
  "m34": {
    "type": "msg",
    "day": 7,
    "time": "10:21",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "If we go with around 11m², that's room for roughly 5–6 toddlers playing there at once. I'll frame the edge with pallets, so there's a low seating border right around the sandbox itself – you'll be able to sit right there and watch her play.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 11
      }
    ],
    "id": "m34",
    "next": "m35"
  },
  "m35": {
    "type": "image",
    "day": 7,
    "time": "10:22",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "toddler sandbox (≈11m²) sketched in, framed by a low pallet seating border",
    "id": "m35",
    "next": "m36"
  },
  "m36": {
    "type": "msg",
    "day": 7,
    "time": "10:26",
    "sender": "Tetiana",
    "initial": "T",
    "bg": "#8f2f5a",
    "fg": "#f7e1ec",
    "text": "Sounds perfect, the little ones really do need their own corner away from the bigger kids 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 5
      }
    ],
    "id": "m36",
    "next": "m37"
  },
  "m37": {
    "type": "msg",
    "day": 7,
    "time": "11:48",
    "sender": "Klaus",
    "initial": "K",
    "bg": "#5a6b8f",
    "fg": "#e6eaf5",
    "text": "We've still got some leftover sand from the raised beds last year, that should help with the build 👍",
    "reactions": [
      {
        "emoji": "♻️",
        "count": 8
      }
    ],
    "id": "m37",
    "next": "m38"
  },
  "m38": {
    "type": "msg",
    "day": 7,
    "time": "11:51",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Nice, every bit we can reuse helps – keeps more of that budget free for other things.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 7
      }
    ],
    "id": "m38",
    "next": "m39"
  },
  "m39": {
    "type": "msg",
    "day": 7,
    "time": "13:42",
    "sender": "Dorota",
    "initial": "D",
    "bg": "#8f7a2f",
    "fg": "#f7f1de",
    "text": "Let's also do sth for the bigger kids! Running and climbing, not just sitting and digging",
    "reactions": [
      {
        "emoji": "👍",
        "count": 16
      },
      {
        "emoji": "🏃",
        "count": 6
      }
    ],
    "id": "m39",
    "next": "m40"
  },
  "m40": {
    "type": "msg",
    "day": 7,
    "time": "13:57",
    "sender": "Lukas",
    "initial": "L",
    "bg": "#2f8f5a",
    "fg": "#dff5e7",
    "text": "Definitely, and somewhere to hide too, my two are obsessed with hide and seek 🙈",
    "reactions": [
      {
        "emoji": "🙈",
        "count": 7
      }
    ],
    "id": "m40",
    "next": "m41"
  },
  "m41": {
    "type": "msg",
    "day": 7,
    "time": "14:23",
    "sender": "Priya",
    "initial": "P",
    "bg": "#8f3d3d",
    "fg": "#f7e3e3",
    "text": "And something to climb on please, otherwise it's just another flat square with a fence around it 😄",
    "reactions": [
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m41",
    "next": "m42"
  },
  "m42": {
    "type": "msg",
    "day": 7,
    "time": "18:14",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Let's do one zone for the older kids then. Biggest share of our ~30 total, so 13-14 at once, around 90m²",
    "reactions": [
      {
        "emoji": "🙌",
        "count": 22
      },
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m42",
    "next": "m43"
  },
  "m43": {
    "type": "msg",
    "day": 7,
    "time": "18:21",
    "sender": "Oleksiy",
    "initial": "O",
    "bg": "#6b8f2f",
    "fg": "#eef5de",
    "text": "Sounds good to me 👍",
    "reactions": [
      {
        "emoji": "👍",
        "count": 6
      }
    ],
    "id": "m43",
    "next": "m44"
  },
  "m44": {
    "type": "transition",
    "toDay": 8,
    "arriveTime": "08:42",
    "id": "m44",
    "next": "m45"
  },
  "m45": {
    "type": "date",
    "day": 8,
    "time": "08:42",
    "text": "Thursday",
    "id": "m45",
    "next": "m46"
  },
  "m46": {
    "type": "msg",
    "day": 8,
    "time": "08:42",
    "sender": "Stefan",
    "initial": "S",
    "bg": "#4f6b99",
    "fg": "#e3eaf5",
    "text": "What about wood chips for the ground in there? Softer if someone trips while climbing or whatever",
    "reactions": [
      {
        "emoji": "👍",
        "count": 12
      }
    ],
    "id": "m46",
    "next": "m47"
  },
  "m47": {
    "type": "msg",
    "day": 8,
    "time": "08:58",
    "sender": "Claudia",
    "initial": "C",
    "bg": "#994f6b",
    "fg": "#f5e3ea",
    "text": "Sounds good, but won't that just spread out everywhere without something holding it in? Tripping hazard along the edges otherwise 💀",
    "reactions": [
      {
        "emoji": "😅",
        "count": 8
      },
      {
        "emoji": "👍",
        "count": 5
      }
    ],
    "id": "m47",
    "next": "m48"
  },
  "m48": {
    "type": "msg",
    "day": 8,
    "time": "09:14",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good catch – a brick border around the edge would solve that, keeps the wood chips contained and gives the zone a clear boundary.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m48",
    "next": "m49"
  },
  "m49": {
    "type": "image",
    "day": 8,
    "time": "09:16",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "brick border now frames the play zone, wood chips filled in",
    "id": "m49",
    "next": "m50"
  },
  "m50": {
    "type": "msg",
    "day": 8,
    "time": "09:18",
    "sender": "Aylin",
    "initial": "A",
    "bg": "#6b3d8f",
    "fg": "#ede2f6",
    "text": "One thing now that I can actually see the shape of it – is the sandbox going to end up right next to this? With both my little one and my older one, I can already picture all that running getting a bit much for her down there",
    "reactions": [
      {
        "emoji": "🙋",
        "count": 7
      }
    ],
    "id": "m50",
    "next": "m51"
  },
  "m51": {
    "type": "msg",
    "day": 8,
    "time": "09:21",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good call – let's give them a bit more breathing room. I'll shift the sandbox a little further along, away from the main zone.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 11
      }
    ],
    "id": "m51",
    "next": "m52"
  },
  "m52": {
    "type": "image",
    "day": 8,
    "time": "09:23",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "sandbox shifted further from the main play zone, more separation between the age groups",
    "id": "m52",
    "next": "m53"
  },
  "m53": {
    "type": "msg",
    "day": 8,
    "time": "09:25",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Just so everyone knows going forward – I can only take on wishes that actually work with the materials and budget we've got.",
    "id": "m53",
    "next": "m54"
  },
  "m54": {
    "type": "msg",
    "day": 8,
    "time": "11:21",
    "sender": "Elif",
    "initial": "E",
    "bg": "#997a4f",
    "fg": "#f5ecdf",
    "text": "What about giving them somewhere to actually hide? Not just open space 🙈",
    "reactions": [
      {
        "emoji": "💡",
        "count": 8
      }
    ],
    "id": "m54",
    "next": "m55"
  },
  "m55": {
    "type": "msg",
    "day": 8,
    "time": "11:36",
    "sender": "Sabine",
    "initial": "S",
    "bg": "#4f9999",
    "fg": "#e0f3f3",
    "text": "A low wall around part of it could work, gives a bit of a hideaway corner 🏰",
    "reactions": [
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m55",
    "next": "m56"
  },
  "m56": {
    "type": "msg",
    "day": 8,
    "time": "11:52",
    "sender": "Marie",
    "initial": "M",
    "bg": "#3d7a8f",
    "fg": "#e2f1f4",
    "text": "Or maybe a little labyrinth in the middle too, way more fun to get lost in than just a wall 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 9
      },
      {
        "emoji": "👍",
        "count": 5
      }
    ],
    "id": "m56",
    "next": "m57"
  },
  "m57": {
    "type": "msg",
    "day": 8,
    "time": "12:07",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Both work well together actually – a circular wall curving around one side for that retreat feel, and a labyrinth in the middle for more active hide-and-seek. Going circular also means nobody can run full-speed into a corner and get hurt.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 13
      },
      {
        "emoji": "🎉",
        "count": 6
      }
    ],
    "id": "m57",
    "next": "m58"
  },
  "m58": {
    "type": "image",
    "day": 8,
    "time": "12:09",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "curved, low wall (no sharp corners) and central labyrinth added to the play zone – wall stays low enough for parents to see over it",
    "id": "m58",
    "next": "m59"
  },
  "m59": {
    "type": "msg",
    "day": 8,
    "time": "12:14",
    "sender": "Sabine",
    "initial": "S",
    "bg": "#4f9999",
    "fg": "#e0f3f3",
    "text": "Speaking of watching them – is there somewhere proper to sit and actually keep an eye on things, or are we all just standing around all summer? 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 6
      }
    ],
    "id": "m59",
    "next": "m60"
  },
  "m60": {
    "type": "msg",
    "day": 8,
    "time": "12:19",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good shout – I'll add a curved pallet bench by the sandbox, and a second one over by the play zone, so there's always a proper seat with a clear view, whichever side you're on.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 14
      }
    ],
    "id": "m60",
    "next": "m61"
  },
  "m61": {
    "type": "image",
    "day": 8,
    "time": "12:21",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "two curved pallet benches added – one by the sandbox, one by the main play zone, each with a clear view for parents",
    "id": "m61",
    "next": "m62"
  },
  "m62": {
    "type": "msg",
    "day": 8,
    "time": "14:18",
    "sender": "Aryan",
    "initial": "A",
    "bg": "#b35c3d",
    "fg": "#fae6dd",
    "text": "And climbing too, that was the other big wish right? Maybe something at the other edge",
    "reactions": [
      {
        "emoji": "👍",
        "count": 12
      }
    ],
    "id": "m62",
    "next": "m63"
  },
  "m63": {
    "type": "msg",
    "day": 8,
    "time": "14:33",
    "sender": "Jens",
    "initial": "J",
    "bg": "#5a8f3d",
    "fg": "#eef6e2",
    "text": "Like a wall they can climb up and jump off? My kids love that kind of thing 😎",
    "reactions": [
      {
        "emoji": "😎",
        "count": 9
      }
    ],
    "id": "m63",
    "next": "m64"
  },
  "m64": {
    "type": "msg",
    "day": 8,
    "time": "14:51",
    "sender": "Soraya",
    "initial": "S",
    "bg": "#c9912e",
    "fg": "#fcf1da",
    "text": "And maybe a small climbing frame too, we've still got loads of pallets sitting in storage, and I've actually seen something like that built before somewhere else, just keep it low for the little ones",
    "reactions": [
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m64",
    "next": "m65"
  },
  "m65": {
    "type": "msg",
    "day": 8,
    "time": "15:09",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Got it – a jumping wall on the other side for the older kids, plus a small, low pallet climbing frame for the little ones. Should cover both age groups well.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 11
      }
    ],
    "id": "m65",
    "next": "m66"
  },
  "m66": {
    "type": "image",
    "day": 8,
    "time": "15:11",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "jumping wall and low pallet climbing frame added on the opposite edge",
    "id": "m66",
    "next": "m67"
  },
  "m67": {
    "type": "msg",
    "day": 8,
    "time": "17:12",
    "sender": "Heike",
    "initial": "H",
    "bg": "#8f4b6b",
    "fg": "#f7e6ec",
    "text": "After all that running around they're gonna want somewhere to just sit for a sec too 😅",
    "reactions": [
      {
        "emoji": "😅",
        "count": 7
      }
    ],
    "id": "m67",
    "next": "m68"
  },
  "m68": {
    "type": "msg",
    "day": 8,
    "time": "17:27",
    "sender": "Ines",
    "initial": "I",
    "bg": "#3d6b5c",
    "fg": "#dcece6",
    "text": "Yeah, maybe something built right into the play area itself, not just benches on the side 💡",
    "reactions": [
      {
        "emoji": "💡",
        "count": 6
      }
    ],
    "id": "m68",
    "next": "m69"
  },
  "m69": {
    "type": "msg",
    "day": 8,
    "time": "17:43",
    "sender": "Karin",
    "initial": "K",
    "bg": "#2f7d4f",
    "fg": "#e1f4e7",
    "text": "Like little brick steps or blocks they can perch on, something solid",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m69",
    "next": "m70"
  },
  "m70": {
    "type": "system",
    "day": 8,
    "time": "17:50",
    "text": "Annika joined the group.",
    "id": "m70",
    "next": "m71"
  },
  "m71": {
    "type": "msg",
    "day": 8,
    "time": "17:52",
    "sender": "Annika",
    "initial": "A",
    "bg": "#a8527a",
    "fg": "#fbe5ee",
    "text": "Just found this group, this is amazing! 😍 I've got two little ones who'd love to join in once it's all built",
    "reactions": [
      {
        "emoji": "👋",
        "count": 14
      },
      {
        "emoji": "❤️",
        "count": 6
      }
    ],
    "id": "m71",
    "next": "m72"
  },
  "m72": {
    "type": "msg",
    "day": 8,
    "time": "17:54",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Welcome, Annika! Glad to have you join in 👋",
    "reactions": [
      {
        "emoji": "👋",
        "count": 8
      }
    ],
    "id": "m72",
    "next": "m73"
  },
  "m73": {
    "type": "msg",
    "day": 8,
    "time": "17:58",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "We can build a fixed seating structure out of small bricks then, right at the edge of the play area, perfect for the kids to perch on for a quick breather mid-game.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m73",
    "next": "m74"
  },
  "m74": {
    "type": "msg",
    "day": 8,
    "time": "18:01",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "If we keep that around 20m², that's room for maybe 3-4 kids at once.",
    "id": "m74",
    "next": "m75"
  },
  "m75": {
    "type": "msg",
    "day": 8,
    "time": "18:02",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "That actually covers most of our ~30 kids now – toddlers in the sandbox, and the older half spread across the main zone. Just the teenagers without a spot of their own so far.",
    "reactions": [
      {
        "emoji": "🎉",
        "count": 24
      },
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m75",
    "next": "m76"
  },
  "m76": {
    "type": "image",
    "day": 8,
    "time": "18:03",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "low brick perches for the kids added along the edge of the play zone",
    "id": "m76",
    "next": "m77"
  },
  "m77": {
    "type": "msg",
    "day": 8,
    "time": "19:32",
    "sender": "Susanne",
    "initial": "S",
    "bg": "#6b3d5c",
    "fg": "#ecdce6",
    "text": "Could we get a table tennis table too? Always such a hit 🏓",
    "reactions": [
      {
        "emoji": "🏓",
        "count": 11
      }
    ],
    "id": "m77",
    "next": "m78"
  },
  "m78": {
    "type": "msg",
    "day": 8,
    "time": "19:47",
    "sender": "Sven",
    "initial": "S",
    "bg": "#534ab7",
    "fg": "#eeedfe",
    "text": "Yes please, last year's was constantly taken, I never even got a turn myself",
    "reactions": [
      {
        "emoji": "😅",
        "count": 6
      }
    ],
    "id": "m78",
    "next": "m79"
  },
  "m79": {
    "type": "msg",
    "day": 8,
    "time": "20:02",
    "sender": "Frank",
    "initial": "F",
    "bg": "#8f6b2f",
    "fg": "#f6eddc",
    "text": "Then let's just do two this time, way less fighting over it 😂",
    "reactions": [
      {
        "emoji": "😂",
        "count": 8
      }
    ],
    "id": "m79",
    "next": "m80"
  },
  "m80": {
    "type": "msg",
    "day": 8,
    "time": "20:15",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Two tables it is. I'll put them on the paved area, away from the little ones so the balls don't end up in the sandbox. That's actually the last piece – toddlers, kids, and now teenagers all have something here.",
    "id": "m80",
    "next": "m81"
  },
  "m81": {
    "type": "image",
    "day": 8,
    "time": "20:17",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "paved area with two table tennis tables – all age groups now covered",
    "id": "m81",
    "next": "m82"
  },
  "m82": {
    "type": "msg",
    "day": 8,
    "time": "20:18",
    "sender": "Aryan",
    "initial": "A",
    "bg": "#b35c3d",
    "fg": "#fae6dd",
    "text": "Looks great, only thing I'd say is move the table tennis tables a bit further from the sandbox, balls might still end up close",
    "reactions": [
      {
        "emoji": "👍",
        "count": 7
      }
    ],
    "id": "m82",
    "next": "m83"
  },
  "m83": {
    "type": "msg",
    "day": 8,
    "time": "20:19",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good point – I'll shift them further along the paved area, more buffer between the two.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m83",
    "next": "m84"
  },
  "m84": {
    "type": "image",
    "day": 8,
    "time": "20:20",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "table tennis tables shifted further from the sandbox",
    "id": "m84",
    "next": "m85"
  },
  "m85": {
    "type": "transition",
    "toDay": 9,
    "arriveTime": "09:16",
    "id": "m85",
    "next": "m86"
  },
  "m86": {
    "type": "date",
    "day": 9,
    "time": "09:16",
    "text": "Friday",
    "id": "m86",
    "next": "m87"
  },
  "m87": {
    "type": "msg",
    "day": 9,
    "time": "09:16",
    "sender": "Sarah",
    "isMe": true,
    "text": "Been quietly following all of this, you guys come up with really cool stuff! Kind of exciting watching it all come together 👀",
    "id": "m87",
    "next": "m88"
  },
  "m88": {
    "type": "msg",
    "day": 9,
    "time": "09:31",
    "sender": "Sarah",
    "isMe": true,
    "text": "As someone without kids myself though, I'd love some nice seating for the rest of us too, not just the parents on bench duty – maybe more pallets with some greenery mixed in, like the ones under the tree 🌿",
    "id": "m88",
    "next": "m89"
  },
  "m89": {
    "type": "msg",
    "day": 9,
    "time": "09:49",
    "sender": "Mariia",
    "initial": "M",
    "bg": "#185fa5",
    "fg": "#e6f1fb",
    "text": "Love that, could even be something the kids help plant themselves, like a little activity on its own 🌱",
    "reactions": [
      {
        "emoji": "🌱",
        "count": 9
      }
    ],
    "id": "m89",
    "next": "m90"
  },
  "m90": {
    "type": "msg",
    "day": 9,
    "time": "10:24",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good thing it's mostly pallets we already have – easy on the budget. The two benches already cover keeping an eye on the kids, so this one's just for atmosphere. I'll bring in some planters too.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 8
      }
    ],
    "id": "m90",
    "next": "m91"
  },
  "m91": {
    "type": "image",
    "day": 9,
    "time": "10:26",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "pallet-and-planter seating added around the square",
    "id": "m91",
    "next": "m92"
  },
  "m92": {
    "type": "msg",
    "day": 9,
    "time": "20:48",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "I think I've got enough now to put a first full layout together. Give me until tomorrow, I'll share it as soon as it's ready 👀",
    "reactions": [
      {
        "emoji": "👀",
        "count": 18
      },
      {
        "emoji": "🔥",
        "count": 7
      }
    ],
    "id": "m92",
    "next": "m93"
  },
  "m93": {
    "type": "transition",
    "toDay": 10,
    "arriveTime": "09:02",
    "id": "m93",
    "next": "m94"
  },
  "m94": {
    "type": "date",
    "day": 10,
    "time": "09:02",
    "text": "Saturday",
    "id": "m94",
    "next": "m95"
  },
  "m95": {
    "type": "file",
    "day": 10,
    "time": "09:02",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "fileName": "WESTHAGENPLAYS!_DRAFT.pdf",
    "fileSub": "PDF document",
    "id": "m95",
    "next": "m96"
  },
  "m96": {
    "type": "msg",
    "day": 10,
    "time": "09:03",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Morning everyone! Pulled it all together overnight – here's the first full layout. Let me know what you think!",
    "reactions": [
      {
        "emoji": "😍",
        "count": 160
      },
      {
        "emoji": "❤️",
        "count": 85
      },
      {
        "emoji": "🎉",
        "count": 110
      }
    ],
    "id": "m96",
    "next": "m97"
  },
  "m97": {
    "type": "msg",
    "day": 10,
    "time": "09:14",
    "sender": "Dorota",
    "initial": "D",
    "bg": "#8f7a2f",
    "fg": "#f7f1de",
    "text": "Wow, this looks amazing, can't believe it's all coming together this fast 😍",
    "reactions": [
      {
        "emoji": "😍",
        "count": 11
      }
    ],
    "id": "m97",
    "next": "m98"
  },
  "m98": {
    "type": "msg",
    "day": 10,
    "time": "09:26",
    "sender": "Priya",
    "initial": "P",
    "bg": "#8f3d3d",
    "fg": "#f7e3e3",
    "text": "The little hideaway corner with the wall is such a nice touch ✨",
    "reactions": [
      {
        "emoji": "👍",
        "count": 8
      }
    ],
    "id": "m98",
    "next": "m99"
  },
  "m99": {
    "type": "msg",
    "day": 10,
    "time": "09:39",
    "sender": "Aryan",
    "initial": "A",
    "bg": "#b35c3d",
    "fg": "#fae6dd",
    "text": "Looks great, the climbing wall especially – my two are going to be straight over there 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 9
      }
    ],
    "id": "m99",
    "next": "m100"
  },
  "m100": {
    "type": "msg",
    "day": 10,
    "time": "10:05",
    "sender": "Nicole",
    "initial": "N",
    "bg": "#5c8fb3",
    "fg": "#e3eff5",
    "text": "Honestly didn't expect this much detail already, nice one 👏",
    "reactions": [
      {
        "emoji": "👏",
        "count": 7
      }
    ],
    "id": "m100",
    "next": "m101"
  },
  "m101": {
    "type": "msg",
    "day": 10,
    "time": "10:18",
    "sender": "Younes",
    "initial": "Y",
    "bg": "#854f0b",
    "fg": "#faeeda",
    "text": "This is gonna be a great summer ☀️",
    "reactions": [
      {
        "emoji": "☀️",
        "count": 9
      }
    ],
    "id": "m101",
    "next": "m102"
  },
  "m102": {
    "type": "msg",
    "day": 10,
    "time": "13:31",
    "sender": "Fatima",
    "initial": "F",
    "bg": "#2f5a8f",
    "fg": "#e1ecf6",
    "text": "One more thought, could we maybe leave a small pile of loose bricks somewhere, just for the kids to build and stack themselves? 🧱",
    "reactions": [
      {
        "emoji": "👍",
        "count": 15
      },
      {
        "emoji": "😄",
        "count": 6
      }
    ],
    "id": "m102",
    "next": "m103"
  },
  "m103": {
    "type": "msg",
    "day": 10,
    "time": "13:45",
    "sender": "Lukas",
    "initial": "L",
    "bg": "#2f8f5a",
    "fg": "#dff5e7",
    "text": "Yes, that kind of free building is honestly half the fun for them 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 6
      }
    ],
    "id": "m103",
    "next": "m104"
  },
  "m104": {
    "type": "msg",
    "day": 10,
    "time": "13:59",
    "sender": "Anja",
    "initial": "A",
    "bg": "#6b8f99",
    "fg": "#e3eff0",
    "text": "Could just go in a corner near the main area, doesn't need its own zone 👍",
    "reactions": [
      {
        "emoji": "👍",
        "count": 7
      }
    ],
    "id": "m104",
    "next": "m105"
  },
  "m105": {
    "type": "msg",
    "day": 10,
    "time": "14:04",
    "sender": "Dorota",
    "initial": "D",
    "bg": "#8f7a2f",
    "fg": "#f7f1de",
    "text": "They can make their own toys, basically 😄",
    "reactions": [
      {
        "emoji": "😄",
        "count": 8
      }
    ],
    "id": "m105",
    "next": "m106"
  },
  "m106": {
    "type": "msg",
    "day": 10,
    "time": "14:08",
    "sender": "Stefan",
    "initial": "S",
    "bg": "#4f6b99",
    "fg": "#e3eaf5",
    "text": "My kid's a little architect already! He's going to love this 🏗️",
    "reactions": [
      {
        "emoji": "🏗️",
        "count": 7
      }
    ],
    "id": "m106",
    "next": "m107"
  },
  "m107": {
    "type": "msg",
    "day": 10,
    "time": "14:13",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Easy addition – I'll add a small loose-brick corner right next to the play area for free building.",
    "id": "m107",
    "next": "m108"
  },
  "m108": {
    "type": "msg",
    "day": 10,
    "time": "14:16",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Let me fold all that into an updated version real quick 👨‍🔧",
    "reactions": [
      {
        "emoji": "👍",
        "count": 9
      }
    ],
    "id": "m108",
    "next": "m109"
  },
  "m109": {
    "type": "image",
    "day": 10,
    "time": "14:19",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "loose-brick corner for free building added next to the play zone",
    "id": "m109",
    "next": "m110"
  },
  "m110": {
    "type": "msg",
    "day": 10,
    "time": "15:32",
    "sender": "Heike",
    "initial": "H",
    "bg": "#8f4b6b",
    "fg": "#f7e6ec",
    "text": "Looking at it again, the open part of the square still feels pretty bare somehow. And there's basically no shade anywhere either",
    "id": "m110",
    "next": "m111"
  },
  "m111": {
    "type": "msg",
    "day": 10,
    "time": "15:35",
    "sender": "Marie",
    "initial": "M",
    "bg": "#3d7a8f",
    "fg": "#e2f1f4",
    "text": "Yeah, in the middle of summer that whole stretch is going to be brutal in direct sun",
    "id": "m111",
    "next": "m112"
  },
  "m112": {
    "type": "msg",
    "day": 10,
    "time": "15:38",
    "sender": "Petra",
    "initial": "P",
    "bg": "#993556",
    "fg": "#fbeaf0",
    "text": "Especially right by the sandbox, toddlers really shouldn't be sitting in full sun for long",
    "id": "m112",
    "next": "m113"
  },
  "m113": {
    "type": "msg",
    "day": 10,
    "time": "15:42",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Good point, all of you – I'll add a few more pallet planters with trees, placed right next to the play elements themselves so they're actually shaded, not just nearby.",
    "id": "m113",
    "next": "m114"
  },
  "m114": {
    "type": "msg",
    "day": 10,
    "time": "15:43",
    "sender": "Karin",
    "initial": "K",
    "bg": "#2f7d4f",
    "fg": "#e1f4e7",
    "text": "Smart, mine completely wilt by mid-afternoon in summer 😅",
    "id": "m114",
    "next": "m115"
  },
  "m115": {
    "type": "image",
    "day": 10,
    "time": "15:46",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "caption": "pallet planters with young trees added directly alongside the play elements for shade",
    "id": "m115",
    "next": "m116"
  },
  "m116": {
    "type": "msg",
    "day": 10,
    "time": "16:05",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "I'll leave this open until this evening in case anyone's got anything else to add.",
    "id": "m116",
    "next": "m117"
  },
  "m117": {
    "type": "msg",
    "day": 10,
    "time": "20:42",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Okay, looks like we've landed on a result. Let's make this official and vote on the design:",
    "reactions": [
      {
        "emoji": "👍",
        "count": 14
      }
    ],
    "id": "m117",
    "next": "m118"
  },
  "m118": {
    "type": "poll",
    "day": 10,
    "time": "20:43",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "question": "Official vote: do we approve this as the final design for the square?",
    "options": [
      "Yes, let's build it!",
      "No, it still needs changes"
    ],
    "id": "m118",
    "next": "m119"
  },
  "m119": {
    "type": "system",
    "day": 10,
    "time": "20:45",
    "text": "Poll is open until Monday.",
    "id": "m119",
    "next": "m120"
  },
  "m120": {
    "type": "transition",
    "toDay": 12,
    "arriveTime": "09:18",
    "pollVotes": [
      562,
      36
    ],
    "id": "m120",
    "next": "m121"
  },
  "m121": {
    "type": "date",
    "day": 12,
    "time": "09:18",
    "text": "Monday",
    "id": "m121",
    "next": "m122"
  },
  "m122": {
    "type": "msg",
    "day": 12,
    "time": "09:18",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Poll's closed – strong yes, 598 of 1,042 voted, 94% in favor. The layout is locked in 🎉",
    "pollVotes": [
      562,
      36
    ],
    "pollClose": true,
    "reactions": [
      {
        "emoji": "🎉",
        "count": 350
      },
      {
        "emoji": "🙌",
        "count": 190
      },
      {
        "emoji": "❤️",
        "count": 100
      }
    ],
    "id": "m122",
    "next": "m123"
  },
  "m123": {
    "type": "file",
    "day": 12,
    "time": "09:19",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "fileName": "WESTHAGENPLAYS!_FINAL.pdf",
    "fileSub": "PDF document",
    "id": "m123",
    "next": "m124"
  },
  "m124": {
    "type": "msg",
    "day": 12,
    "time": "09:19",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Here's the finished design, print-ready 📄",
    "id": "m124",
    "next": "m125"
  },
  "m125": {
    "type": "file",
    "day": 12,
    "time": "09:20",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "fileName": "WESTHAGENPLAYS!_BUILD_MANUAL.pdf",
    "fileSub": "PDF document",
    "id": "m125",
    "next": "m126"
  },
  "m126": {
    "type": "msg",
    "day": 12,
    "time": "09:20",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "...and here's the build manual – step-by-step instructions for putting together the playground 🛠️",
    "reactions": [
      {
        "emoji": "🙌",
        "count": 22
      }
    ],
    "id": "m126",
    "next": "m127"
  },
  "m127": {
    "type": "msg",
    "day": 12,
    "time": "09:23",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Heads up though – this still needs to get approved by the city. I'll be in touch the moment everything's ready.",
    "reactions": [
      {
        "emoji": "👍",
        "count": 10
      }
    ],
    "id": "m127",
    "next": "m128"
  },
  "m128": {
    "type": "msg",
    "day": 12,
    "time": "09:26",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Not too worried about the budget part, though – we recycled a lot and barely touched it. Should be enough left for at least one more event later this year 🎉",
    "reactions": [
      {
        "emoji": "🎉",
        "count": 14
      },
      {
        "emoji": "👍",
        "count": 8
      }
    ],
    "id": "m128",
    "next": "m129"
  },
  "m129": {
    "type": "fastForward",
    "fromDay": 12,
    "toDay": 26,
    "arriveTime": "08:44",
    "id": "m129",
    "next": "m130"
  },
  "m130": {
    "type": "date",
    "day": 26,
    "time": "08:44",
    "text": "Monday",
    "id": "m130",
    "next": "m131"
  },
  "m131": {
    "type": "msg",
    "day": 26,
    "time": "08:44",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Update: permit's through, materials are in 👍 and I've pencilled in Saturday, July 1st, for the build.",
    "reactions": [
      {
        "emoji": "🎉",
        "count": 220
      },
      {
        "emoji": "🙌",
        "count": 120
      },
      {
        "emoji": "👍",
        "count": 90
      }
    ],
    "id": "m131",
    "next": "m132"
  },
  "m132": {
    "type": "msg",
    "day": 26,
    "time": "08:46",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Here's what we'll actually need hands for on the day, and roughly how many for each:",
    "id": "m132",
    "next": "m133"
  },
  "m133": {
    "type": "poll",
    "day": 26,
    "time": "08:47",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "multi": true,
    "question": "What could you help with on the day?",
    "options": [
      "Brickwork",
      "Pallet & wood building",
      "Spreading sand & wood chips",
      "Planting & greenery",
      "Hauling & transport",
      "Food & drinks",
      "Keeping the kids busy"
    ],
    "needed": [
      8,
      6,
      5,
      4,
      5,
      6,
      6
    ],
    "id": "m133",
    "next": "m134"
  },
  "m134": {
    "type": "system",
    "day": 26,
    "time": "08:49",
    "text": "Poll is open for the rest of the week.",
    "id": "m134",
    "next": "m135"
  },
  "m135": {
    "type": "msg",
    "day": 26,
    "time": "09:12",
    "sender": "Klaus",
    "initial": "K",
    "bg": "#5a6b8f",
    "fg": "#e6eaf5",
    "text": "Signed up for brickwork, done enough of that by now 😄",
    "pollVotes": [
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "id": "m135",
    "next": "m136"
  },
  "m136": {
    "type": "msg",
    "day": 26,
    "time": "09:26",
    "sender": "Birgit",
    "initial": "B",
    "bg": "#993c1d",
    "fg": "#fae8e0",
    "text": "I'll take food and drinks, someone has to keep people fed 🥪",
    "pollVotes": [
      1,
      0,
      0,
      0,
      0,
      1,
      0
    ],
    "reactions": [
      {
        "emoji": "🥪",
        "count": 6
      }
    ],
    "id": "m136",
    "next": "m137"
  },
  "m137": {
    "type": "msg",
    "day": 26,
    "time": "09:41",
    "sender": "Stefan",
    "initial": "S",
    "bg": "#4f6b99",
    "fg": "#e3eaf5",
    "text": "Hauling for me, bringing the trailer again",
    "pollVotes": [
      1,
      0,
      0,
      0,
      1,
      1,
      0
    ],
    "id": "m137",
    "next": "m138"
  },
  "m138": {
    "type": "msg",
    "day": 26,
    "time": "12:18",
    "sender": "Elif",
    "initial": "E",
    "bg": "#997a4f",
    "fg": "#f5ecdf",
    "text": "Putting myself down for planting, could use the excuse to finally get my hands dirty 🌿",
    "pollVotes": [
      1,
      0,
      0,
      1,
      1,
      1,
      0
    ],
    "id": "m138",
    "next": "m139"
  },
  "m139": {
    "type": "msg",
    "day": 26,
    "time": "15:53",
    "sender": "Tetiana",
    "initial": "T",
    "bg": "#8f2f5a",
    "fg": "#f7e1ec",
    "text": "I'll help keep the kids entertained while the adults are busy building 🙂",
    "pollVotes": [
      1,
      0,
      0,
      1,
      1,
      1,
      1
    ],
    "id": "m139",
    "next": "m140"
  },
  "m140": {
    "type": "msg",
    "day": 26,
    "time": "18:07",
    "sender": "Jana",
    "initial": "J",
    "bg": "#2f8f7a",
    "fg": "#dff5f0",
    "text": "Can't make the day itself, but signed up to drop off materials beforehand 📦",
    "id": "m140",
    "next": "m141"
  },
  "m141": {
    "type": "msg",
    "day": 26,
    "time": "20:31",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Looking solid across the board already, thanks for jumping in 🙌",
    "reactions": [
      {
        "emoji": "👏",
        "count": 28
      },
      {
        "emoji": "🙌",
        "count": 14
      }
    ],
    "id": "m141",
    "next": "m142"
  },
  "m142": {
    "type": "msg",
    "day": 26,
    "time": "20:38",
    "sender": "Sarah",
    "isMe": true,
    "text": "Sign me up for whatever's still needed, just excited to finally meet everyone in person after weeks of chatting here 😍😍",
    "id": "m142",
    "next": "m143"
  },
  "m143": {
    "type": "transition",
    "toDay": 1,
    "toMonth": "July",
    "arriveTime": "08:30",
    "id": "m143",
    "next": "m144"
  },
  "m144": {
    "type": "date",
    "day": 1,
    "time": "08:30",
    "text": "Saturday",
    "id": "m144",
    "next": "m145"
  },
  "m145": {
    "type": "event",
    "day": 1,
    "time": "08:30",
    "text": "📅 Building Day!",
    "id": "m145",
    "next": "m146"
  },
  "m146": {
    "type": "msg",
    "day": 1,
    "time": "08:30",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "Morning, everyone! Hope you're all feeling motivated – let's get this built 🙌",
    "reactions": [
      {
        "emoji": "🎉",
        "count": 48
      },
      {
        "emoji": "💪",
        "count": 31
      }
    ],
    "id": "m146",
    "next": "m147"
  },
  "m147": {
    "type": "msg",
    "day": 1,
    "time": "08:32",
    "sender": "Klaus",
    "initial": "K",
    "bg": "#5a6b8f",
    "fg": "#e6eaf5",
    "text": "Been looking forward to this all week, let's go! 💪",
    "id": "m147",
    "next": "m148"
  },
  "m148": {
    "type": "msg",
    "day": 1,
    "time": "08:33",
    "sender": "Birgit",
    "initial": "B",
    "bg": "#993c1d",
    "fg": "#fae8e0",
    "text": "So excited, see you all there ☀️",
    "id": "m148",
    "next": "m149"
  },
  "m149": {
    "type": "msg",
    "day": 1,
    "time": "08:35",
    "sender": "Tetiana",
    "initial": "T",
    "bg": "#8f2f5a",
    "fg": "#f7e1ec",
    "text": "Can't wait to see it all come together today!",
    "id": "m149",
    "next": "m150"
  },
  "m150": {
    "type": "msg",
    "day": 1,
    "time": "08:38",
    "sender": "Westhagen Marktplatz",
    "initial": "L",
    "bg": "#BF5468",
    "fg": "#fbe7ea",
    "text": "One more thing – if anyone's unsure exactly where a piece goes, point your phone at the square and it'll show you where everything lines up:",
    "ctaButton": "📍 Show placement on site",
    "id": "m150",
    "next": null
  }
};
const START_NODE = "m1";
